### ISSUE TITLE
found java level deadlock please provide the solution

### ISSUE THREAD

**Issue by peerit12** [spotify/threaddump-analyzer#12]
# Found one Java-level deadlock:

```
"ajp-bio-18009-exec-1189":
  waiting to lock monitor 0x00007f70c0f1c228 (object 0x0000000765282180, a org.apache.jasper.servlet.JspServletWrapper),
  which is held by "ajp-bio-18009-exec-1021"
"ajp-bio-18009-exec-1021":
  waiting to lock monitor 0x00007f70c052cb70 (object 0x00000007502c73d0, a com.newrelic.weave.weavepackage.CachedWeavePackage),
  which is held by "ajp-bio-18009-exec-377"
"ajp-bio-18009-exec-377":
  waiting to lock monitor 0x00007f70c055bb68 (object 0x00000007500be800, a org.apache.catalina.loader.WebappClassLoader),
  which is held by "ajp-bio-18009-exec-386"
"ajp-bio-18009-exec-386":
  waiting to lock monitor 0x00007f70c052cb70 (object 0x00000007502c73d0, a com.newrelic.weave.weavepackage.CachedWeavePackage),
  which is held by "ajp-bio-18009-exec-377"
```
# Java stack information for the threads listed above:

```
"ajp-bio-18009-exec-1189":
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:355)
    - waiting to lock <0x0000000765282180> (a org.apache.jasper.servlet.JspServletWrapper)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:389)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:333)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:304)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:684)
    at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:593)
    at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:530)
    at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:927)
    at org.apache.jasper.runtime.PageContextImpl.include(PageContextImpl.java:652)
    at org.apache.struts.tiles.TilesUtilImpl.doInclude(TilesUtilImpl.java:137)
    at org.apache.struts.tiles.TilesUtil.doInclude(TilesUtil.java:177)
    at org.apache.struts.taglib.tiles.InsertTag.doInclude(InsertTag.java:756)
    at org.apache.struts.taglib.tiles.InsertTag$InsertHandler.doEndTag(InsertTag.java:881)
    at org.apache.struts.taglib.tiles.InsertTag.doEndTag(InsertTag.java:473)
    at org.apache.jsp.jsp.layouts.strutstemplate_jsp._jspx_meth_tiles_005finsert_005f2(strutstemplate_jsp.java:693)
    at org.apache.jsp.jsp.layouts.strutstemplate_jsp._jspService(strutstemplate_jsp.java:516)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:433)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:389)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:333)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:304)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:684)
    at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:471)
    at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:402)
    at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:329)
    at org.apache.struts.action.RequestProcessor.doForward(RequestProcessor.java:1069)
    at org.apache.struts.tiles.TilesRequestProcessor.doForward(TilesRequestProcessor.java:274)
    at org.apache.struts.tiles.TilesRequestProcessor.processTilesDefinition(TilesRequestProcessor.java:254)
    at org.apache.struts.tiles.TilesRequestProcessor.processForwardConfig(TilesRequestProcessor.java:309)
    at com.appnetix.app.control.web.AppnetixRequestProcessor.process(AppnetixRequestProcessor.java:203)
    at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
    at com.appnetix.app.control.web.AppnetixControllerServlet.doGet(AppnetixControllerServlet.java:827)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:304)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at com.appnetix.app.control.web.filter.UserLocalFilter.doFilter(UserLocalFilter.java:59)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:175)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:462)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:164)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:851)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:405)
    at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:196)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:515)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:300)
    - locked <0x00000007480022f0> (a org.apache.tomcat.util.net.SocketWrapper)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
"ajp-bio-18009-exec-1021":
    at com.newrelic.weave.weavepackage.WeavePackageManager.validateAgainstClassLoader(WeavePackageManager.java:216)
    - waiting to lock <0x00000007502c73d0> (a com.newrelic.weave.weavepackage.CachedWeavePackage)
    at com.newrelic.weave.weavepackage.WeavePackageManager.getSuccessfulValidation(WeavePackageManager.java:191)
    at com.newrelic.weave.weavepackage.WeavePackageManager.match(WeavePackageManager.java:137)
    at com.newrelic.weave.weavepackage.WeavePackageManager.weave(WeavePackageManager.java:160)
    at com.newrelic.agent.instrumentation.weaver.ClassWeaverService.transform(ClassWeaverService.java:548)
    at com.newrelic.agent.instrumentation.context.InstrumentationContextManager$2.transform(InstrumentationContextManager.java:205)
    at sun.instrument.TransformerManager.transform(TransformerManager.java:169)
    at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:365)
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:132)
    - locked <0x00000007735339e8> (a org.apache.jasper.servlet.JasperLoader)
    at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:63)
    at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:124)
    at org.apache.jasper.servlet.JspServletWrapper.getServlet(JspServletWrapper.java:172)
    - locked <0x0000000765282180> (a org.apache.jasper.servlet.JspServletWrapper)
    at org.apache.jasper.servlet.JspServletWrapper.getDependants(JspServletWrapper.java:289)
    at org.apache.jasper.compiler.Compiler.isOutDated(Compiler.java:488)
    at org.apache.jasper.compiler.Compiler.isOutDated(Compiler.java:425)
    at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:637)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:358)
    - locked <0x0000000765282180> (a org.apache.jasper.servlet.JspServletWrapper)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:389)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:333)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:304)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:684)
    at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:593)
    at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:530)
    at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:927)
    at org.apache.jasper.runtime.PageContextImpl.include(PageContextImpl.java:652)
    at org.apache.struts.tiles.TilesUtilImpl.doInclude(TilesUtilImpl.java:137)
    at org.apache.struts.tiles.TilesUtil.doInclude(TilesUtil.java:177)
    at org.apache.struts.taglib.tiles.InsertTag.doInclude(InsertTag.java:756)
    at org.apache.struts.taglib.tiles.InsertTag$InsertHandler.doEndTag(InsertTag.java:881)
    at org.apache.struts.taglib.tiles.InsertTag.doEndTag(InsertTag.java:473)
    at org.apache.jsp.jsp.layouts.strutstemplate_jsp._jspx_meth_tiles_005finsert_005f2(strutstemplate_jsp.java:693)
    at org.apache.jsp.jsp.layouts.strutstemplate_jsp._jspService(strutstemplate_jsp.java:516)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:433)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:389)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:333)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:304)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:684)
    at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:471)
    at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:402)
    at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:329)
    at org.apache.struts.action.RequestProcessor.doForward(RequestProcessor.java:1069)
    at org.apache.struts.tiles.TilesRequestProcessor.doForward(TilesRequestProcessor.java:274)
    at org.apache.struts.tiles.TilesRequestProcessor.processTilesDefinition(TilesRequestProcessor.java:254)
    at org.apache.struts.tiles.TilesRequestProcessor.processForwardConfig(TilesRequestProcessor.java:309)
    at com.appnetix.app.control.web.AppnetixRequestProcessor.process(AppnetixRequestProcessor.java:203)
    at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
    at com.appnetix.app.control.web.AppnetixControllerServlet.doGet(AppnetixControllerServlet.java:827)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:304)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at com.appnetix.app.control.web.filter.UserLocalFilter.doFilter(UserLocalFilter.java:59)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:175)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:462)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:164)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:851)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:405)
    at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:196)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:515)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:300)
    - locked <0x000000075d03a058> (a org.apache.tomcat.util.net.SocketWrapper)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
"ajp-bio-18009-exec-377":
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java)
    - waiting to lock <0x00000007500be800> (a org.apache.catalina.loader.WebappClassLoader)
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1523)
    at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:126)
    - locked <0x0000000770a6bf08> (a org.apache.jasper.servlet.JasperLoader)
    at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:63)
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at sun.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.newrelic.weave.weavepackage.NewClassAppender.loadClassesInTopologicalOrder(NewClassAppender.java:75)
    at com.newrelic.weave.weavepackage.NewClassAppender.appendClasses(NewClassAppender.java:45)
    - locked <0x0000000770a6bf08> (a org.apache.jasper.servlet.JasperLoader)
    at com.newrelic.weave.weavepackage.WeavePackageManager.validateAgainstClassLoader(WeavePackageManager.java:235)
    - locked <0x00000007502c73d0> (a com.newrelic.weave.weavepackage.CachedWeavePackage)
    at com.newrelic.weave.weavepackage.WeavePackageManager.getSuccessfulValidation(WeavePackageManager.java:191)
    at com.newrelic.weave.weavepackage.WeavePackageManager.match(WeavePackageManager.java:137)
    at com.newrelic.weave.weavepackage.WeavePackageManager.weave(WeavePackageManager.java:160)
    at com.newrelic.agent.instrumentation.weaver.ClassWeaverService.transform(ClassWeaverService.java:548)
    at com.newrelic.agent.instrumentation.context.InstrumentationContextManager$2.transform(InstrumentationContextManager.java:205)
    at sun.instrument.TransformerManager.transform(TransformerManager.java:169)
    at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:365)
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:132)
    - locked <0x0000000770a6bf08> (a org.apache.jasper.servlet.JasperLoader)
    at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:63)
    at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:124)
    at org.apache.jasper.servlet.JspServletWrapper.getServlet(JspServletWrapper.java:172)
    - locked <0x0000000770a4e600> (a org.apache.jasper.servlet.JspServletWrapper)
    at org.apache.jasper.servlet.JspServletWrapper.getDependants(JspServletWrapper.java:289)
    at org.apache.jasper.compiler.Compiler.isOutDated(Compiler.java:488)
    at org.apache.jasper.compiler.Compiler.isOutDated(Compiler.java:425)
    at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:637)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:358)
    - locked <0x0000000770a4e600> (a org.apache.jasper.servlet.JspServletWrapper)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:389)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:333)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:304)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at com.appnetix.app.control.web.filter.UserLocalFilter.doFilter(UserLocalFilter.java:59)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:175)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:462)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:164)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:851)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:405)
    at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:196)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:515)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:300)
    - locked <0x0000000754f0fda0> (a org.apache.tomcat.util.net.SocketWrapper)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
"ajp-bio-18009-exec-386":
    at com.newrelic.weave.weavepackage.WeavePackageManager.validateAgainstClassLoader(WeavePackageManager.java:216)
    - waiting to lock <0x00000007502c73d0> (a com.newrelic.weave.weavepackage.CachedWeavePackage)
    at com.newrelic.weave.weavepackage.WeavePackageManager.getSuccessfulValidation(WeavePackageManager.java:191)
    at com.newrelic.weave.weavepackage.WeavePackageManager.match(WeavePackageManager.java:137)
    at com.newrelic.weave.weavepackage.WeavePackageManager.weave(WeavePackageManager.java:160)
    at com.newrelic.agent.instrumentation.weaver.ClassWeaverService.transform(ClassWeaverService.java:548)
    at com.newrelic.agent.instrumentation.context.InstrumentationContextManager$2.transform(InstrumentationContextManager.java:205)
    at sun.instrument.TransformerManager.transform(TransformerManager.java:169)
    at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:365)
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2820)
    - locked <0x00000007500be800> (a org.apache.catalina.loader.WebappClassLoader)
    at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1150)
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1645)
    - locked <0x00000007500be800> (a org.apache.catalina.loader.WebappClassLoader)
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1523)
    at com.appnetix.app.control.web.LeadServlet.<clinit>(LeadServlet.java:47)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at java.lang.Class.newInstance0(Class.java:355)
    at java.lang.Class.newInstance(Class.java:308)
    at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:119)
    at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1087)
    - locked <0x00000007508d9c70> (a org.apache.catalina.core.StandardWrapper)
    at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:824)
    - locked <0x00000007508d9c70> (a org.apache.catalina.core.StandardWrapper)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:135)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:175)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:462)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:164)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:851)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:405)
    at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:196)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:515)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:300)
    - locked <0x00000007577552c8> (a org.apache.tomcat.util.net.SocketWrapper)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)

Found 1 deadlock.
```

**Comment by walles** [comment]
I've updated the thread dump analyzer to support the thread dump format you pasted.

Except for that this seems to be a problem with your app rather than a problem with the thread dump analyzer, and that you'll have to look into yourself.

  Regards /Johan
