### ISSUE TITLE
(websphere 6.1, java 1.5) jdbc connection pool is full 

### ISSUE THREAD

**Issue by somkid1234** [spotify/threaddump-analyzer#29]
00000010 HttpSessDRSBu E   storeObject: Caught Exception while trying to serialize. Stack trace: java.io.NotSerializableException: org.apache.commons.fileupload.DeferredFileOutputStream
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1135)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1490)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1462)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1404)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1133)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1490)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1462)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1404)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1133)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1490)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1462)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1404)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1133)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:346)
        at com.ibm.ws.webcontainer.httpsession.HttpSessDRSBuffWrapper.getBytes(HttpSessDRSBuffWrapper.java:269)
        at com.ibm.ws.webcontainer.httpsession.HttpSessDRSBuffWrapper.storeObject(HttpSessDRSBuffWrapper.java:119)
        at com.ibm.ws.webcontainer.httpsession.DRSBackedHashtable.handlePropertyHits(DRSBackedHashtable.java:294)
        at com.ibm.ws.webcontainer.httpsession.DRSBackedHashtable.persistSession(DRSBackedHashtable.java:378)
        at com.ibm.ws.webcontainer.httpsession.BackedHashtable.ejbStore(BackedHashtable.java:2665)
        at com.ibm.ws.webcontainer.httpsession.BackedHashtable.storeSession(BackedHashtable.java:2298)
        at com.ibm.ws.webcontainer.httpsession.BackedHashtable.put(BackedHashtable.java:2937)
        at com.ibm.ws.webcontainer.httpsession.DatabaseSessionContext.sync(DatabaseSessionContext.java:158)
        at com.ibm.ws.webcontainer.httpsession.SessionData.sync(SessionData.java:314)
        at com.ibm.ws.webcontainer.httpsession.DatabaseSessionData.sync(DatabaseSessionData.java:928)
        at com.ibm.ws.webcontainer.httpsession.DatabaseSessionContext.checkForSessionWrites(DatabaseSessionContext.java:672)
        at com.ibm.ws.webcontainer.httpsession.DatabaseSessionContext.asyncExternalWrite(DatabaseSessionContext.java:509)
        at com.ibm.ws.webcontainer.httpsession.SessionAlarmListener.alarm(SessionAlarmListener.java:61)
        at com.ibm.ejs.util.am._Alarm.run(_Alarm.java:91)
        at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1593)

**Comment by somkid1234** [comment]
Please help me from information my issue is application can not create new pool to database
I don't know root cause why jdbc id full

**Comment by walles** [comment]
What you have posted here is not a thread dump (it's a stack trace), so it cannot be used with the Thread Dump Analyzer.

Also, [Java 1.5 reached End of Life in November 2009](https://www.java.com/en/download/faq/java_5_eol.xml); more than ten years ago, so you should consider upgrading.

And I have never used Websphere ever, and have no idea what could be causing this.

I'll close this ticket, since I can't think of any code changes to this repo that would help resolving it.
