### ISSUE TITLE
Only finds one thread

### ISSUE THREAD

**Issue by rconn01** [spotify/threaddump-analyzer#7]
I am trying to analyze a thread dump that was captured using visualvm, when I place it in the analyzer it comes back as only finding one thread, there are a few hundred threads in the thread dump. The view just shows all the threads in one really long line. Is there some special format that the input text needs to be in so the parser can recognize each individual thread?

**Comment by rconn01** [comment]
It appears this [case](https://github.com/spotify/threaddump-analyzer/blob/f87739f76ba8c0050aa83c6e0b6e9544cad0fc82/analyze.js#L592) fails since `prio=` is not contained in the stacks so it just treats it all as one really big multi lined thread name.

Changing that if case to also check for `Thread.State` seems to make things work. Not sure if that breaks the true functionality or not though

Here is an example of one of the stacks

```
"http-bio-8810-exec-147" - Thread t@96965
   java.lang.Thread.State: TIMED_WAITING
    at sun.misc.Unsafe.park(Native Method)
    - parking to wait for <162718e5> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2082)
    at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
    at org.apache.tomcat.util.threads.TaskQueue.poll(TaskQueue.java:86)
    at org.apache.tomcat.util.threads.TaskQueue.poll(TaskQueue.java:32)
    at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
```
